#arranque de los servicios para crear las imagenes y crear los ambientes
services:
  rpm-builder:
    build:
      context: ..
      dockerfile: "Imagen 1 – Gestión de RPMs/Dockerfile"
    container_name: rpm-builder

  ruby-environment:
    build:
      context: ..
      dockerfile: "Imagen 2 – Ruby y rbenv/Dockerfile"
    container_name: ruby-environment

  node-environment:
    build:
      context: ..
      dockerfile: "Imagen 3 – Node.js y Yarn/Dockerfile"
    container_name: node-environment

  python-environment:
    build:
      context: ..
      dockerfile: "Imagen 4 – Python/Dockerfile"
    container_name: python-environment

  full-environment:
    build:
      context: ..
      dockerfile: "Imagen 5 – Imagen Full/Dockerfile"
    container_name: full-environment

    